### ISSUE TITLE
Alt text

### ISSUE THREAD

**Issue by farishkash** [Chris1113/Dasmotos-website-#1]
https://github.com/Chris1113/Dasmotos-website-/blob/b8f70ea01f82453957e575099b4822f786316b59/index.html#L12

Start using Alt text for each image.  This helps with accessibility.  The visually impaired use the screen readers on their computers, smartphones and this will read this aloud to describe the picture.

**Comment by Chris1113** [comment]
OK, shall I add this Alt text?

**Comment by Chris1113** [comment]
I have amended the files and re uploaded them. Thanks
