### ISSUE TITLE
Font family repetition

### ISSUE THREAD

**Issue by farishkash** [Chris1113/Dasmotos-website-#2]
https://github.com/Chris1113/Dasmotos-website-/blob/b8f70ea01f82453957e575099b4822f786316b59/style.css#L3

As a general rule, whenever a style is being repeated, always see what options are available in CSS to reduce this.

In this case, since the font family is the same throughout the website, you can use the universal selector.
```
* {
  font-family: Helvetica; 
}
```

**Comment by Chris1113** [comment]
Thank you
