### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by farishkash** [Chris1113/Dasmotos-website-#3]
https://github.com/Chris1113/Dasmotos-website-/blob/b8f70ea01f82453957e575099b4822f786316b59/index.html#L5

Make sure the title matches the company name.  Companies and Clients get upset when their trademarks and names aren't exact.  The title is what shows up on the tab bar in browsers.

**Comment by Chris1113** [comment]
I will bear this in mind for the future. Thanks
