### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by farishkash** [Chris1113/Dasmotos-website-#4]
Overall met expectations

In this first project, I look at two primary items with the main goal being to stop inefficient or bad practices early.

First, did you use divs, ids/classes to manage and organize your HTML.
Great on this, very good class usage such as those **thosedarnprices.**

Second is your CSS efficient and non-repetitive.
Font family is a common issue in this first submission, my goal with the mentioning of this, is to make you aware of your options.

Alt text should be used in all images in general, I like to mention this as early as possible.

To prepare you for the upcoming projects I like you to go to flexboxfroggy.com. See how far you can get, the later projects uses flexbox heavily and this will help you immensely.

**Comment by Chris1113** [comment]
Thanks for the comments. 
I will use the frog site as requested and use the font-family * in the future to avoid repetition.
